language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - python -m unittest tests/*.py
deploy:
  provider: pypi
  user: ginger
  password:
    secure: bFfRy4le7z0H7YAex35TUNEWSMRtgbZNlqk8MIGd72RmK36/7jmO4Fwg3qUP5XsL4qcdfGicO+7qB9ecMoK8oeOCS9peS2oJqdrfbXJSUNgXl2aT078bDzaJ2S6kWqUHaaSFXQEDw/7pOqoSYNKDReZH0aPPtJqPxt1kwuZTfTQ8mO+G1wkQ+mDizoKf1M29WXz82NJ3CEDuBtv7x5l9ztxHOnDJwtwR/ABrYExYQhSXOL7ZNcNVGhq9zBd1yD6iF/PRpPTZzdWn6tKvDTaYYwYyb2ux9GkAm1hry74YZ3uXVYEUmLnKUZdGEzFAO4O+0BQ5z7YsJivQD/cXLQvzesJaaTgQ7JqVr6ea1EKiMXPqbf4KUvHHgvnX9sc38fTlRrLzHIBTM/j2hz9Y5/wrRT3LJxyfNv3AU3QQiipZ0VRny0YM0ufNIBI9fdjmZDIn5qb3FJC03XNyM+eoZuManhJG3AxRSBRuWenO+TknD2rWjr4UXzkWSW63A1CGl7sHQjy2lQIVPXTDqUuvByEqw7GxfyxijFMUtg1YT0fxbsUy2Br6wdJ6L/bqdpA3qIJZ78dr+/0/L4W7T52vwK0Im6FkLmpLFMAqneAz/slFCc0voUB3aGS2AR419aEKLsfEtZj7WkqSIfaiJh+2B2f8n3z0qC2mnVXRvDtsqyVOpAY=
  skip_existing: true
  on:
    tags: true
